### ISSUE TITLE
Base: display bonded tokens and status instead of voting power for inactive validators

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-2.0-cosmos#556]
All inactive validators will have no voting power. It seems redundant to show all having 0 voting power. 

![image](https://user-images.githubusercontent.com/932636/143194508-6aea1eec-2906-4f8d-a7fc-973504140314.png)

We may instead show the bonded tokens which is how many tokens are still being delegated to the inactive validators. `Unbonding` and `Unbonded` validators are still different as their bonded tokens will be treated differently. One entitle slashing but the other not.

**Comment by ryuash** [comment]
Ok i will remove the VP column and add a status column indicating if they are `unbonded` `unbonding` or `jailed`

**Comment by ryuash** [comment]
@kwunyeung 
Since we have a **All Validators** tab i would prefer if we kept the table same all across the 3 tabs to avoid weird jumpiness, otherwise i would not be sure what columns to display for **All Validators**

Below I have added a `status` column and put in a ticket with [bdjuno](https://github.com/forbole/bdjuno) to get the `tombstone` status.

I've also displayed the total tokens still bonded while displaying the VP is 0% if the validator is not active.

![image](https://user-images.githubusercontent.com/42913823/143518681-cce19910-3b39-4cf6-b95c-23dc0d2f216e.png)
