### ISSUE TITLE
https://likecoin.bigdipper.live/ Latest Height is About 100 Blocks Behind

### ISSUE THREAD

**Issue by smarttreeTech** [forbole/big-dipper-2.0-cosmos#613]
<img width="718" alt="Screen Shot 2021-12-20 at 9 49 13 PM" src="https://user-images.githubusercontent.com/71287400/146857066-0f34a661-92b5-4c14-8a64-952eeda454a3.png">
<img width="659" alt="Screen Shot 2021-12-20 at 9 49 37 PM" src="https://user-images.githubusercontent.com/71287400/146857120-250ddad9-5c1f-4890-be02-b124ece5f5ba.png">

Please see the snapshot for details. Thank you.

**Comment by ryuash** [comment]
Will ask the bdjuno team to take a look and see what's causing the lag

**Comment by ryuash** [comment]
Update: They are debugging to find the bottleneck. I'll do some status updates here once I have more information

**Comment by ryuash** [comment]
Update: Likecoin seems to be back on track. Seems the archive node was under a lot of pressure and was unable to catch up. We have since then redirected bdjuno to a fullnode. It is missing some blocks in between but believe there is an issue opened with the bdjuno team to re-parse the missing blocks.

Closing. Feel free to reopen if there is any questions
